# Database configuration
hibernate.connection.driver_class=com.mysql.cj.jdbc.Driver
hibernate.connection.url=jdbc:mysql://localhost:3306/gestion_stock?createDatabaseIfNotExist=true
hibernate.connection.username=root
hibernate.connection.password=

# Hibernate properties
hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
hibernate.hbm2ddl.auto=update
hibernate.show_sql=true
hibernate.format_sql=true
hibernate.use_sql_comments=true

# Connection pool
hibernate.connection.pool_size=10
